import 'package:cloud_firestore/cloud_firestore.dart';

enum RequestStatus { pending, approved, rejected }

class UserRequestModel {
  final String uid; // generated by Firebase Auth after approval
  final String name;
  final String email;
  final String role;
  final DateTime requestedAt;
  final RequestStatus status;

  UserRequestModel({
    required this.name,
    required this.email,
    required this.role,
    this.status = RequestStatus.pending,
    DateTime? requestedAt,
  }) : uid = '', // placeholder until approved
       requestedAt = requestedAt ?? DateTime.now();

  factory UserRequestModel.fromMap(Map<String, dynamic> map) =>
      UserRequestModel(
        name: map['name'] as String? ?? '',
        email: map['email'] as String,
        role: map['role'] as String? ?? 'birim_sekreteri',
        requestedAt: (map['requestedAt'] as Timestamp?)?.toDate(),
        status: RequestStatus.values.firstWhere(
          (s) => s.name == map['status'],
          orElse: () => RequestStatus.pending,
        ),
      );

  Map<String, dynamic> toMap() => {
    'name': name,
    'email': email,
    'role': role,
    'requestedAt': Timestamp.fromDate(requestedAt),
    'status': status.name,
  };
}
